config/routes.rb
Coder::Application.routes.draw do
  
  resources :sub_categories
  match 'recipe_search' => 'recipes#search'
  get "home/logout"
  match 'home/logout' => 'home#logout'
  match 'login' => 'home#login'
  get "home/index"

  match 'authenticate' => 'home#authenticate'

  resources :recipes

  resources :user_profiles

  resources :users
  
  

   root :to => "home#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  require 'will_paginate'
  
  has_attached_file :avatar
  #cattr_reader :per_page
  #@@per_page = 3
  
  # new columns need to be added here to be writable through mass assignment
  #attr_accessible :user_id, :user_name, :name, :is_veg, :category, :sub_category, :video,:rating, :tag, :steps, :comments, :avatar_file_name, :avatar_content_type, :avatar_file_size, :avatar_updated_at
  
  validates_presence_of :name

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'will_paginate'
  before_filter :protect
  
  # GET /recipes
  # GET /recipes.xml
  def index
    #@recipes = Recipe.all
    @recipes = Recipe.paginate :page => params[:page],:per_page => 3, :order => 'created_at DESC'
    #@recipes = Recipe.paginate :per_page => 2, :page=>params[:page]
    #@recipes = Recipe.paginate :per_page => 10, :page => params[:recipe_page],:order => 'name ASC'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @user=User.find(session[:user])
    params[:recipe][:user_id]=session[:user]
    params[:recipe][:user_name]=@user.name
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(recipes_path, :notice => 'Recipe was successfully created.') }
        format.xml  { render :xml => recipes_path, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @user=User.find(session[:user])
    params[:recipe][:user_id]=session[:user]
    params[:recipe][:user_name]=@user.name
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end

  def search
    @user=User.find(session[:user])
    @query = params[:search] || ''
    @recipes = Recipe.paginate :page => params[:page],:per_page => 3, :conditions=>["name like ?","#{@query}%"], :order => 'created_at DESC'
    #@recipes = Recipe.find(:all, :conditions=>["name like ?","#{@query}%"])
    if @recipes.blank?
      puts 'ueeeeeeeeeeeeeeeeeeerrrrrrrrrr'
      flash[:notice] = 'No recipe matched your search criteria.'
      redirect_to @user
    end
    
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<script type="text/javascript">
var subCat = new Array();
<% @sub_categories=SubCategory.find(:all) -%>
<% for sub_category in @sub_categories -%>
  subCat.push(new Array('<%= sub_category.category_id %>', '<%=h sub_category.category_id %>', '<%= sub_category.sub_category %>'));
<% end -%>
alert("subCat "+subCat);
function categorySelected() {
alert("hii");
  category_id = $('recipe_category').value;
  alert("category_id "+category_id);
  options = $('recipe_sub_category').options;
  alert("options "+options);
  options.length = 1;
  subCat.each(function(sub) {
    if (sub[0] == category_id) {
      options[options.length] = new Option(sub[1], sub[2]);
    }
  });

}

  document.observe('dom:loaded', function() {
  categorySelected();
  $('recipe_category').observe('onchange', categorySelected);
  });
</script>

<%= form_for @recipe, :html => { :multipart => true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :recipe_name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_veg %><br />
    <%= f.check_box :is_veg %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    
    <select name="recipe[category]" id="recipe_category"  >
						 <option value="1">Indian</option>
						 <option value="2">Chineese</option>
						 <option value="3">Continental</option> </select>

  </div>
  <div class="field">
    <%= f.label :sub_category %><br />
    <%= f.collection_select :sub_category, SubCategory.find(:all), :id, :sub_category, :include_blank => true  %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_area :video, :size=>"25x4" %>
  </div>
  <div class="field">
    <%= f.label :steps %><br />
    <%= f.text_area :steps, :size=>"25x4" %>
  </div>

  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :tag, :size=>"25x4" %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_recipe_listing.html.erb
<%= render :partial=> 'search_bar'%>
<table cellspacing="0" cellpadding="10px" border="1">
<% unless @recipes.blank? %>
	<tr>
		<th>S NO</th><th>Recipe Name</th><th>User Name</th><th>Category</th>
	</tr>

  <% @recipes.each_with_index do |recipe,index| %>
	<tr>
		<td><%= index+1 %></td><td><%= recipe.name %></td><td><%= recipe.user_name %></td><td><%= recipe.category %></td>
	</tr>
  <% end %> 
<% end %>
</table>

app/views/recipes/_search_bar.html.erb
  <div id="test" style="padding:7px;">
    <form name="search_form"  action="/recipe_search"  method="get">
      <input id="search_input" autocomplete="off" type="text" name="search" size="25" />
      <input id="search_button" type="submit" value="Search Recipes" />
    </form>
  </div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing Recipes</h1>

<table cellspacing="0" cellpadding="10px" border="1">
  <tr>
    <th>S No</th>
    <th>User name</th>
    <th>Name</th>
    <th>Rating</th>
    <% if session[:permission]=='admin'%>
    <th colspan="3">Actions</th>
    <%end%>
  </tr>

<% @recipes.each_with_index do |recipe, index| %>
  <tr>
    <td><%= index+1 %></td>
    <td><% if recipe.user_id==session[:user] %>You<% else %><%= recipe.user_name %><% end %></td>
    <td><%= link_to recipe.name, recipe %></td>
    <td><%= recipe.rating %></td>
    <% if session[:permission]=='admin'%>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, :confirm => 'Are you sure want to detete this Recipe?', :method => :delete %></td>
    <%end%>
  </tr>
<% end %>
</table>


<br />



<b><%= will_paginate @recipes %></b>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/search.html.erb
<%= render :partial=> 'search_bar'%>
<table cellspacing="0" cellpadding="10px" border="1">
<% unless @recipes.blank? %>
	<tr>
		<th>S NO</th><th>Recipe Name</th><th>User Name</th><th>Category</th>
	</tr>

  <% @recipes.each_with_index do |recipe,index| %>
	<tr>
		<td><%= index+1 %></td><td><%= recipe.name %></td><td><%= recipe.user_name %></td><td><%= recipe.category %></td>
	</tr>
  <% end %> 
<% end %>
</table>

<b><b><%= will_paginate @recipes %></b></b>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>


<p>
  <b>User name:</b>
  <%= @recipe.user_name %>
</p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Is veg:</b>
  <%= @recipe.is_veg %>
</p>


<p>
    <b>Image:</b><br />
	<%= image_tag @recipe.avatar.url, :border=>"2", :size=>"120x120" %>
<p>
  <b>Category:</b>
  <%= @recipe.category %>
</p>
<p>
  <b>Sub Category:</b>
  <%= @recipe.sub_category %>
</p>
<p>
  <b>Steps:</b>
  <%= @recipe.steps %>
</p>
<p>
  <b>Comments:</b>
  <%= @recipe.comments %>
</p>
<p>
  <b>Tag:</b>
  <%= @recipe.tag %>
</p>
  <b>Rating:</b>
  <%= @recipe.rating %>
</p>
<% if session[:permission]=='admin' or session[:user]==@recipe.user_id %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<% end %>
<%= link_to 'Back', recipes_path %>