config/routes.rb
Coder::Application.routes.draw do
  
  resources :sub_categories
  match 'recipe_search' => 'recipes#search'
  get "home/logout"
  match 'home/logout' => 'home#logout'
  match 'login' => 'home#login'
  get "home/index"

  match 'authenticate' => 'home#authenticate'

  resources :recipes

  resources :user_profiles

  resources :users
  
  

   root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :user_profile
  
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :name, :email, :password, :password_confirmation,:permission,:dob
  #attr_accessor :password
  
  validates_presence_of :name, :email, :password
  validates_format_of :name, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_length_of :password, :minimum => 4, :allow_blank => true
  validates_confirmation_of :password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :protect, :except => [:new, :create]
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    
    if params[:user][:permission]=='admin'
    
    @chk=User.find_by_permission('admin')
                if @chk.blank?
                      if @user.save
                        redirect_to(login_path, :notice => 'User was successfully created.') 
                      else
                        render :action => "new" 
                      end      
                else
                      flash[:notice]="Only one Admin user allowed"
                      render :action => "new"
                end
          
    else
                if @user.save
                  #session[:user]=@user.id
                  redirect_to(login_path, :notice => 'User was successfully created.') 
                else
                  render :action => "new" 
                end      
    end



    
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= javascript_include_tag 'jquery' %>
<%= javascript_include_tag 'rails.validations' %>
<%= stylesheet_link_tag 'scaffold', :media => "all" %>

<%= form_for @user, :validate => true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :Password_Confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :DOB %><br />
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.select(:permission, [['Admin', 'admin'], ['User', 'user']]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_profile_path(@user.user_profile.id) %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.user_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render :partial=> 'recipes/search_bar'%>

<fieldset>
<legend><b><%=@user.name%>'s Index</b></legend>

<div style="padding-left:20px;">
	<%= link_to "Users Home",  recipes_path%><br />
	<% if @user.user_profile.blank? %>
		<%= link_to "User Profile",  new_user_profile_path%><br />
	<% else %>
		<%= link_to "User Profile",  user_profile_path(@user.user_profile.id)%><br />
	<% end %>
	<%= link_to "Manage Recipes",  new_recipe_path%><br />
	<% if session[:permission]=='admin'%>
		<%= link_to "Add/Remove Sub categories", sub_categories_path %><br />
	<% end %>
</fieldset>