config/routes.rb
Coder::Application.routes.draw do
  
  resources :sub_categories
  match 'recipe_search' => 'recipes#search'
  get "home/logout"
  match 'home/logout' => 'home#logout'
  match 'login' => 'home#login'
  get "home/index"

  match 'authenticate' => 'home#authenticate'

  resources :recipes

  resources :user_profiles

  resources :users
  
  

   root :to => "home#index"

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :profile_name, :address, :phone, :mobile, :user_id, :gender
    
  validates_numericality_of :phone, :mobile
  validates_length_of :profile_name, :maximum => 256
  validates_length_of :address, :maximum => 500

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_filter :protect
  # GET /user_profiles
  # GET /user_profiles.xml
  def index
    @user_profiles = UserProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_profiles }
    end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.xml
  def show
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.xml
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.xml
  def create
    params[:user_profile][:user_id]=session[:user]
    
    @user_profile = UserProfile.new(params[:user_profile])
    @user=User.find(session[:user])
    
      if @user_profile.save
         redirect_to(@user, :notice => 'User profile was successfully created.')         
      else
         render :action => "new"
      end
   
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.xml
  def update
    @user_profile = UserProfile.find(params[:id])
    @user=User.find(session[:user])
    respond_to do |format|
      if @user_profile.update_attributes(params[:user_profile])
        format.html { redirect_to(@user, :notice => 'User profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.xml
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to(user_profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= javascript_include_tag 'jquery' %>
<%= javascript_include_tag 'rails.validations' %>
<%= stylesheet_link_tag 'scaffold', :media => "all" %>

<%= form_for @user_profile , :validate => true do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Profile_Name %><br />
    <%= f.text_field :profile_name %>
  </div>
 
 <div class="field">
    <%= f.label :gender %><br />
    <%= f.radio_button(:gender, 'Male') %> Male
    <%= f.radio_button(:gender, 'Female') %> Female
 </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, :size=>'25x4' %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing User Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_path(@user_profile.user) %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <tr>
    <th>User</th>
    <th>Profile name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Mobile</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_profiles.each do |user_profile| %>
  <tr>
    <td><%= user_profile.user_id %></td>
    <td><%= user_profile.profile_name %></td>
    <td><%= user_profile.address %></td>
    <td><%= user_profile.phone %></td>
    <td><%= user_profile.mobile %></td>
    <td><%= link_to 'Show', user_profile %></td>
    <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
    <td><%= link_to 'Destroy', user_profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p>
  <b>Profile Name:</b>
  <%= @user_profile.profile_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @user_profile.gender %>
</p>

<p>
  <b>Address:</b>
  <%= @user_profile.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @user_profile.phone %>
</p>

<p>
  <b>Mobile:</b>
  <%= @user_profile.mobile %>
</p>


<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_path(@user_profile.user) %>