config/routes.rb
Coder::Application.routes.draw do
  
  resources :sub_categories
  match 'recipe_search' => 'recipes#search'
  get "home/logout"
  match 'home/logout' => 'home#logout'
  match 'login' => 'home#login'
  get "home/index"

  match 'authenticate' => 'home#authenticate'

  resources :recipes

  resources :user_profiles

  resources :users
  
  

   root :to => "home#index"

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  # GET /sub_categories
  # GET /sub_categories.xml
  def index
    @sub_categories = SubCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sub_categories }
    end
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.xml
  def show
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/new
  # GET /sub_categories/new.xml
  def new
    @sub_category = SubCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  # POST /sub_categories
  # POST /sub_categories.xml
  def create
    @sub_category = SubCategory.new(params[:sub_category])

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully created.') }
        format.xml  { render :xml => @sub_category, :status => :created, :location => @sub_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categories/1
  # PUT /sub_categories/1.xml
  def update
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      if @sub_category.update_attributes(params[:sub_category])
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.xml
  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to(sub_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.radio_button(:category_id, 1) %> Indian
    <%= f.radio_button(:category_id, 2) %> Chineese
    <%= f.radio_button(:category_id, 3) %> Continental
  </div>
  <div class="field">
    <%= f.label :sub_category %><br />
    <%= f.text_field :sub_category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing sub_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<h1>Listing Sub Categories</h1>

<table cellpadding="10px" cellspacing="0" border="1">
  <tr>
    <th>Category</th>
    <th>Sub Category</th>
    <th colspan="3">Actions</th>
  </tr>

<% @sub_categories.each do |sub_category| %>
  <tr>
    <td><%= sub_category.category_id %></td>
    <td><%= sub_category.sub_category %></td>
    <td><%= link_to 'Show', sub_category %></td>
    <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
    <td><%= link_to 'Destroy', sub_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @sub_category.category_id %>
</p>

<p>
  <b>Sub Category:</b>
  <%= @sub_category.sub_category %>
</p>


<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>